### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by TeeThanakit** [G2U-CPE36/G2U_docs#1]
### What happened?
The current documentation does not include instructions on how to set up LaTeX on operating systems like Windows and macOS.

### Expected result:
Please provide step-by-step setup guides for:
- **Windows**
- **macOS**

**Comment by YuilTripathee** [comment]
Stop inventing bro

**Comment by TeeThanakit** [comment]
complete it broo gg

**Comment by TeeThanakit** [comment]
its good now thx
